### PR TITLE
Charge_Rate_Bug_Fixed

### PR DESCRIPTION
**Pull request by gaurav-iitb**

### CODE REVIEW

**Comment by FireCubeStudios** [comment]
Just wondering what is the .dstore files GitHub is showing

**Comment by gaurav-iitb** [comment]
hi I have deleted all the ds_store files. Can now my pr be merged?
Thank You!!

**Comment by FireCubeStudios** [comment]
yep

**Comment by FireCubeStudios** [comment]
Thanks so much!

**Pull request merged**
